#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Material_Range_Bar_Wrapper.Resource", IsApplication=false)]

namespace Material_Range_Bar_Wrapper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public static int barWeight = 2130771973;
			
			// aapt resource value: 0x7f010012
			public static int connectingLineColor = 2130771986;
			
			// aapt resource value: 0x7f010011
			public static int connectingLineWeight = 2130771985;
			
			// aapt resource value: 0x7f010008
			public static int pinColor = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public static int pinMaxFont = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public static int pinMinFont = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int pinPadding = 2130771978;
			
			// aapt resource value: 0x7f010013
			public static int pinRadius = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public static int rangeBar = 2130771983;
			
			// aapt resource value: 0x7f010006
			public static int rangeBarColor = 2130771974;
			
			// aapt resource value: 0x7f01000d
			public static int rangeBarPaddingBottom = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int selectorColor = 2130771982;
			
			// aapt resource value: 0x7f010009
			public static int selectorSize = 2130771977;
			
			// aapt resource value: 0x7f010010
			public static int temporaryPins = 2130771984;
			
			// aapt resource value: 0x7f010007
			public static int textColor = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int tickColor = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int tickEnd = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int tickHeight = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int tickInterval = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int tickStart = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int rotate = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int roundrect = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public static int AppBaseTheme = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int AppTheme = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RangeBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 5
			public static int RangeBar_barWeight = 5;
			
			// aapt resource value: 18
			public static int RangeBar_connectingLineColor = 18;
			
			// aapt resource value: 17
			public static int RangeBar_connectingLineWeight = 17;
			
			// aapt resource value: 8
			public static int RangeBar_pinColor = 8;
			
			// aapt resource value: 12
			public static int RangeBar_pinMaxFont = 12;
			
			// aapt resource value: 11
			public static int RangeBar_pinMinFont = 11;
			
			// aapt resource value: 10
			public static int RangeBar_pinPadding = 10;
			
			// aapt resource value: 19
			public static int RangeBar_pinRadius = 19;
			
			// aapt resource value: 15
			public static int RangeBar_rangeBar = 15;
			
			// aapt resource value: 6
			public static int RangeBar_rangeBarColor = 6;
			
			// aapt resource value: 13
			public static int RangeBar_rangeBarPaddingBottom = 13;
			
			// aapt resource value: 14
			public static int RangeBar_selectorColor = 14;
			
			// aapt resource value: 9
			public static int RangeBar_selectorSize = 9;
			
			// aapt resource value: 16
			public static int RangeBar_temporaryPins = 16;
			
			// aapt resource value: 7
			public static int RangeBar_textColor = 7;
			
			// aapt resource value: 4
			public static int RangeBar_tickColor = 4;
			
			// aapt resource value: 1
			public static int RangeBar_tickEnd = 1;
			
			// aapt resource value: 3
			public static int RangeBar_tickHeight = 3;
			
			// aapt resource value: 2
			public static int RangeBar_tickInterval = 2;
			
			// aapt resource value: 0
			public static int RangeBar_tickStart = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
