#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Example.Resource", IsApplication=true)]

namespace Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Material_Range_Bar_Wrapper.Resource.Attribute.barWeight = global::Example.Resource.Attribute.barWeight;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.connectingLineColor = global::Example.Resource.Attribute.connectingLineColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.connectingLineWeight = global::Example.Resource.Attribute.connectingLineWeight;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.pinColor = global::Example.Resource.Attribute.pinColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.pinMaxFont = global::Example.Resource.Attribute.pinMaxFont;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.pinMinFont = global::Example.Resource.Attribute.pinMinFont;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.pinPadding = global::Example.Resource.Attribute.pinPadding;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.pinRadius = global::Example.Resource.Attribute.pinRadius;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.rangeBar = global::Example.Resource.Attribute.rangeBar;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.rangeBarColor = global::Example.Resource.Attribute.rangeBarColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.rangeBarPaddingBottom = global::Example.Resource.Attribute.rangeBarPaddingBottom;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.selectorColor = global::Example.Resource.Attribute.selectorColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.selectorSize = global::Example.Resource.Attribute.selectorSize;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.temporaryPins = global::Example.Resource.Attribute.temporaryPins;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.textColor = global::Example.Resource.Attribute.textColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.tickColor = global::Example.Resource.Attribute.tickColor;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.tickEnd = global::Example.Resource.Attribute.tickEnd;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.tickHeight = global::Example.Resource.Attribute.tickHeight;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.tickInterval = global::Example.Resource.Attribute.tickInterval;
			global::Material_Range_Bar_Wrapper.Resource.Attribute.tickStart = global::Example.Resource.Attribute.tickStart;
			global::Material_Range_Bar_Wrapper.Resource.Drawable.rotate = global::Example.Resource.Drawable.rotate;
			global::Material_Range_Bar_Wrapper.Resource.Drawable.roundrect = global::Example.Resource.Drawable.roundrect;
			global::Material_Range_Bar_Wrapper.Resource.String.app_name = global::Example.Resource.String.app_name;
			global::Material_Range_Bar_Wrapper.Resource.Style.AppBaseTheme = global::Example.Resource.Style.AppBaseTheme;
			global::Material_Range_Bar_Wrapper.Resource.Style.AppTheme = global::Example.Resource.Style.AppTheme;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar = global::Example.Resource.Styleable.RangeBar;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_barWeight = global::Example.Resource.Styleable.RangeBar_barWeight;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_connectingLineColor = global::Example.Resource.Styleable.RangeBar_connectingLineColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_connectingLineWeight = global::Example.Resource.Styleable.RangeBar_connectingLineWeight;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_pinColor = global::Example.Resource.Styleable.RangeBar_pinColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_pinMaxFont = global::Example.Resource.Styleable.RangeBar_pinMaxFont;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_pinMinFont = global::Example.Resource.Styleable.RangeBar_pinMinFont;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_pinPadding = global::Example.Resource.Styleable.RangeBar_pinPadding;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_pinRadius = global::Example.Resource.Styleable.RangeBar_pinRadius;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_rangeBar = global::Example.Resource.Styleable.RangeBar_rangeBar;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_rangeBarColor = global::Example.Resource.Styleable.RangeBar_rangeBarColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_rangeBarPaddingBottom = global::Example.Resource.Styleable.RangeBar_rangeBarPaddingBottom;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_selectorColor = global::Example.Resource.Styleable.RangeBar_selectorColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_selectorSize = global::Example.Resource.Styleable.RangeBar_selectorSize;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_temporaryPins = global::Example.Resource.Styleable.RangeBar_temporaryPins;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_textColor = global::Example.Resource.Styleable.RangeBar_textColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_tickColor = global::Example.Resource.Styleable.RangeBar_tickColor;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_tickEnd = global::Example.Resource.Styleable.RangeBar_tickEnd;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_tickHeight = global::Example.Resource.Styleable.RangeBar_tickHeight;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_tickInterval = global::Example.Resource.Styleable.RangeBar_tickInterval;
			global::Material_Range_Bar_Wrapper.Resource.Styleable.RangeBar_tickStart = global::Example.Resource.Styleable.RangeBar_tickStart;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int barWeight = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int connectingLineColor = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int connectingLineWeight = 2130771985;
			
			// aapt resource value: 0x7f010008
			public const int pinColor = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int pinMaxFont = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int pinMinFont = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int pinPadding = 2130771978;
			
			// aapt resource value: 0x7f010013
			public const int pinRadius = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int rangeBar = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int rangeBarColor = 2130771974;
			
			// aapt resource value: 0x7f01000d
			public const int rangeBarPaddingBottom = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int selectorColor = 2130771982;
			
			// aapt resource value: 0x7f010009
			public const int selectorSize = 2130771977;
			
			// aapt resource value: 0x7f010010
			public const int temporaryPins = 2130771984;
			
			// aapt resource value: 0x7f010007
			public const int textColor = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int tickColor = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int tickEnd = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int tickHeight = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int tickInterval = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int tickStart = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rotate = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int roundrect = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int notrangebar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int rangebar = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RangeBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 5
			public const int RangeBar_barWeight = 5;
			
			// aapt resource value: 18
			public const int RangeBar_connectingLineColor = 18;
			
			// aapt resource value: 17
			public const int RangeBar_connectingLineWeight = 17;
			
			// aapt resource value: 8
			public const int RangeBar_pinColor = 8;
			
			// aapt resource value: 12
			public const int RangeBar_pinMaxFont = 12;
			
			// aapt resource value: 11
			public const int RangeBar_pinMinFont = 11;
			
			// aapt resource value: 10
			public const int RangeBar_pinPadding = 10;
			
			// aapt resource value: 19
			public const int RangeBar_pinRadius = 19;
			
			// aapt resource value: 15
			public const int RangeBar_rangeBar = 15;
			
			// aapt resource value: 6
			public const int RangeBar_rangeBarColor = 6;
			
			// aapt resource value: 13
			public const int RangeBar_rangeBarPaddingBottom = 13;
			
			// aapt resource value: 14
			public const int RangeBar_selectorColor = 14;
			
			// aapt resource value: 9
			public const int RangeBar_selectorSize = 9;
			
			// aapt resource value: 16
			public const int RangeBar_temporaryPins = 16;
			
			// aapt resource value: 7
			public const int RangeBar_textColor = 7;
			
			// aapt resource value: 4
			public const int RangeBar_tickColor = 4;
			
			// aapt resource value: 1
			public const int RangeBar_tickEnd = 1;
			
			// aapt resource value: 3
			public const int RangeBar_tickHeight = 3;
			
			// aapt resource value: 2
			public const int RangeBar_tickInterval = 2;
			
			// aapt resource value: 0
			public const int RangeBar_tickStart = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
